name: duraq
description: A durable queuing system implemented in Dart
version: 0.0.1
homepage: https://github.com/stephanfeb/duraq

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqlite3: ^2.1.0
  path: ^1.8.0
  isar: ^3.1.0+1
  uuid: ^4.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7
